### PR TITLE
backend setup

### PR DESCRIPTION
**Pull request by summyalena**
### I have finished the setup of the rails api app.
- I ensured there were no linter errors
- I ensured gitflow was followed judiciously.

### CODE REVIEW

**Review by Munsa1 — CHANGES_REQUESTED** [review]
Hi @summyalena, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no link to the backend repo in the front end readme file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rloterh** [comment]
@summyalena 
Kindly remove the logo from the ReadMe of your frontend!

Cheers!

**Review by rloterh — COMMENTED** [review]
Hi Alena, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Kindly ensure to remove the Microverse template logo **from your frontend ReadMe**. Optionally, you can replace it with your own logo if you have one.
- [ ] Your frontend is not running correctly due to `axios` not defined in the _package.json_. Kindly fix this issue.

Setup Error:
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @summyalena, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏

## Required Changes ♻️
- Hello, Here is what I am getting after connecting rails Api and React. I would advise you to display random greetings and submit them again for review.
-  NB: The servers are running perfectly
Capture



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
